### ISSUE TITLE
I get ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

### ISSUE THREAD

**Issue by alekin2** [charlesmalafosse/sports-betting-customloss#1]
history = model.fit(train_x, train_y, validation_data=(test_x, test_y),
          epochs=200, batch_size=5, callbacks=[EarlyStopping(patience=25),
                                                ModelCheckpoint('odds_loss.hdf5',
                                                                save_best_only=True)])
Traceback (most recent call last):
  File "C:\Users\utente\AppData\Local\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-5ee8ac562398>", line 2, in <module>
    history = model.fit(train_x, train_y, validation_data=(test_x, test_y),
  File "C:\Users\utente\AppData\Local\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\utente\AppData\Local\anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 102, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

**Comment by alekin2** [comment]
I've resolved adding:
train_x = np.asarray(train_x).astype(np.float32)
train_y = np.asarray(train_y).astype(np.float32)
test_x = np.asarray(test_x).astype(np.float32)
test_y = np.asarray(test_y).astype(np.float32)
